/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErpRouteImport } from './routes/_erp'
import { Route as ErpClientesIndexRouteImport } from './routes/_erp/clientes/index'
import { Route as ErpClientesIdRouteImport } from './routes/_erp/clientes/$id'
import { Route as ErpComprasIndexRouteImport } from './routes/_erp/compras/index'
import { Route as ErpComprasCotizacionesRouteImport } from './routes/_erp/compras/cotizaciones'
import { Route as ErpComprasGastosRouteImport } from './routes/_erp/compras/gastos'
import { Route as ErpComprasNuevaRouteImport } from './routes/_erp/compras/nueva'
import { Route as ErpComprasOrdenesRouteImport } from './routes/_erp/compras/ordenes'
import { Route as ErpConfiguracionIndexRouteImport } from './routes/_erp/configuracion/index'
import { Route as ErpInventarioIndexRouteImport } from './routes/_erp/inventario/index'
import { Route as ErpInventarioAjustesRouteImport } from './routes/_erp/inventario/ajustes'
import { Route as ErpInventarioCriticoRouteImport } from './routes/_erp/inventario/critico'
import { Route as ErpInventarioDevolucionesRouteImport } from './routes/_erp/inventario/devoluciones'
import { Route as ErpInventarioFisicoRouteImport } from './routes/_erp/inventario/fisico'
import { Route as ErpInventarioHistoricoRouteImport } from './routes/_erp/inventario/historico'
import { Route as ErpInventarioKardexRouteImport } from './routes/_erp/inventario/kardex'
import { Route as ErpInventarioMovimientosRouteImport } from './routes/_erp/inventario/movimientos'
import { Route as ErpInventarioTransferenciasRouteImport } from './routes/_erp/inventario/transferencias'
import { Route as ErpPosIndexRouteImport } from './routes/_erp/pos/index'
import { Route as ErpPosAnticiposRouteImport } from './routes/_erp/pos/anticipos'
import { Route as ErpPosCajasRouteImport } from './routes/_erp/pos/cajas'
import { Route as ErpPosVentaRapidaRouteImport } from './routes/_erp/pos/venta-rapida'
import { Route as ErpProductosIndexRouteImport } from './routes/_erp/productos/index'
import { Route as ErpProductosCategoriasRouteImport } from './routes/_erp/productos/categorias'
import { Route as ErpProductosDescuentosRouteImport } from './routes/_erp/productos/descuentos'
import { Route as ErpProductosLineasRouteImport } from './routes/_erp/productos/lineas'
import { Route as ErpProductosMarcasRouteImport } from './routes/_erp/productos/marcas'
import { Route as ErpProductosPromocionesRouteImport } from './routes/_erp/productos/promociones'
import { Route as ErpProductosServiciosRouteImport } from './routes/_erp/productos/servicios'
import { Route as ErpProveedoresIndexRouteImport } from './routes/_erp/proveedores/index'
import { Route as ErpProveedoresIdRouteImport } from './routes/_erp/proveedores/$id'
import { Route as ErpReportesIndexRouteImport } from './routes/_erp/reportes/index'
import { Route as ErpReportesCobranzasRouteImport } from './routes/_erp/reportes/cobranzas'
import { Route as ErpReportesInventarioRouteImport } from './routes/_erp/reportes/inventario'
import { Route as ErpReportesTallerRouteImport } from './routes/_erp/reportes/taller'
import { Route as ErpReportesVentasRouteImport } from './routes/_erp/reportes/ventas'
import { Route as ErpUsuariosIndexRouteImport } from './routes/_erp/usuarios/index'
import { Route as ErpUsuariosIdRouteImport } from './routes/_erp/usuarios/$id'
import { Route as ErpUsuariosPermisosRouteImport } from './routes/_erp/usuarios/permisos'
import { Route as ErpUsuariosRolesRouteImport } from './routes/_erp/usuarios/roles'
import { Route as ErpUsuariosSedesRouteImport } from './routes/_erp/usuarios/sedes'
import { Route as ErpTallerBahiasIndexRouteImport } from './routes/_erp/taller/bahias/index'
import { Route as ErpTallerCalidadIndexRouteImport } from './routes/_erp/taller/calidad/index'
import { Route as ErpTallerCitasIndexRouteImport } from './routes/_erp/taller/citas/index'
import { Route as ErpTallerDiagnosticosIndexRouteImport } from './routes/_erp/taller/diagnosticos/index'
import { Route as ErpTallerEntregasIndexRouteImport } from './routes/_erp/taller/entregas/index'
import { Route as ErpTallerHistorialIndexRouteImport } from './routes/_erp/taller/historial/index'
import { Route as ErpTallerInspeccionesIndexRouteImport } from './routes/_erp/taller/inspecciones/index'
import { Route as ErpTallerInspeccionesIdRouteImport } from './routes/_erp/taller/inspecciones/$id'
import { Route as ErpTallerOrdenesIndexRouteImport } from './routes/_erp/taller/ordenes/index'
import { Route as ErpTallerOrdenesIdRouteImport } from './routes/_erp/taller/ordenes/$id'
import { Route as ErpTallerPresupuestosIndexRouteImport } from './routes/_erp/taller/presupuestos/index'
import { Route as ErpTallerRecepcionIndexRouteImport } from './routes/_erp/taller/recepcion/index'
import { Route as ErpTallerVehiculosIndexRouteImport } from './routes/_erp/taller/vehiculos/index'
import { Route as ErpTallerVehiculosIdRouteImport } from './routes/_erp/taller/vehiculos/$id'
import { Route as ErpTallerWipIndexRouteImport } from './routes/_erp/taller/wip/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpRoute = ErpRouteImport.update({
  id: '/_erp',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpClientesIndexRoute = ErpClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpClientesIdRoute = ErpClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpComprasIndexRoute = ErpComprasIndexRouteImport.update({
  id: '/compras/',
  path: '/compras/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpComprasCotizacionesRoute = ErpComprasCotizacionesRouteImport.update({
  id: '/compras/cotizaciones',
  path: '/compras/cotizaciones',
  getParentRoute: () => ErpRoute,
} as any)
const ErpComprasGastosRoute = ErpComprasGastosRouteImport.update({
  id: '/compras/gastos',
  path: '/compras/gastos',
  getParentRoute: () => ErpRoute,
} as any)
const ErpComprasNuevaRoute = ErpComprasNuevaRouteImport.update({
  id: '/compras/nueva',
  path: '/compras/nueva',
  getParentRoute: () => ErpRoute,
} as any)
const ErpComprasOrdenesRoute = ErpComprasOrdenesRouteImport.update({
  id: '/compras/ordenes',
  path: '/compras/ordenes',
  getParentRoute: () => ErpRoute,
} as any)
const ErpConfiguracionIndexRoute = ErpConfiguracionIndexRouteImport.update({
  id: '/configuracion/',
  path: '/configuracion/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpInventarioIndexRoute = ErpInventarioIndexRouteImport.update({
  id: '/inventario/',
  path: '/inventario/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpInventarioAjustesRoute = ErpInventarioAjustesRouteImport.update({
  id: '/inventario/ajustes',
  path: '/inventario/ajustes',
  getParentRoute: () => ErpRoute,
} as any)
const ErpInventarioCriticoRoute = ErpInventarioCriticoRouteImport.update({
  id: '/inventario/critico',
  path: '/inventario/critico',
  getParentRoute: () => ErpRoute,
} as any)
const ErpInventarioDevolucionesRoute =
  ErpInventarioDevolucionesRouteImport.update({
    id: '/inventario/devoluciones',
    path: '/inventario/devoluciones',
    getParentRoute: () => ErpRoute,
  } as any)
const ErpInventarioFisicoRoute = ErpInventarioFisicoRouteImport.update({
  id: '/inventario/fisico',
  path: '/inventario/fisico',
  getParentRoute: () => ErpRoute,
} as any)
const ErpInventarioHistoricoRoute = ErpInventarioHistoricoRouteImport.update({
  id: '/inventario/historico',
  path: '/inventario/historico',
  getParentRoute: () => ErpRoute,
} as any)
const ErpInventarioKardexRoute = ErpInventarioKardexRouteImport.update({
  id: '/inventario/kardex',
  path: '/inventario/kardex',
  getParentRoute: () => ErpRoute,
} as any)
const ErpInventarioMovimientosRoute =
  ErpInventarioMovimientosRouteImport.update({
    id: '/inventario/movimientos',
    path: '/inventario/movimientos',
    getParentRoute: () => ErpRoute,
  } as any)
const ErpInventarioTransferenciasRoute =
  ErpInventarioTransferenciasRouteImport.update({
    id: '/inventario/transferencias',
    path: '/inventario/transferencias',
    getParentRoute: () => ErpRoute,
  } as any)
const ErpPosIndexRoute = ErpPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpPosAnticiposRoute = ErpPosAnticiposRouteImport.update({
  id: '/pos/anticipos',
  path: '/pos/anticipos',
  getParentRoute: () => ErpRoute,
} as any)
const ErpPosCajasRoute = ErpPosCajasRouteImport.update({
  id: '/pos/cajas',
  path: '/pos/cajas',
  getParentRoute: () => ErpRoute,
} as any)
const ErpPosVentaRapidaRoute = ErpPosVentaRapidaRouteImport.update({
  id: '/pos/venta-rapida',
  path: '/pos/venta-rapida',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProductosIndexRoute = ErpProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProductosCategoriasRoute = ErpProductosCategoriasRouteImport.update({
  id: '/productos/categorias',
  path: '/productos/categorias',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProductosDescuentosRoute = ErpProductosDescuentosRouteImport.update({
  id: '/productos/descuentos',
  path: '/productos/descuentos',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProductosLineasRoute = ErpProductosLineasRouteImport.update({
  id: '/productos/lineas',
  path: '/productos/lineas',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProductosMarcasRoute = ErpProductosMarcasRouteImport.update({
  id: '/productos/marcas',
  path: '/productos/marcas',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProductosPromocionesRoute = ErpProductosPromocionesRouteImport.update({
  id: '/productos/promociones',
  path: '/productos/promociones',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProductosServiciosRoute = ErpProductosServiciosRouteImport.update({
  id: '/productos/servicios',
  path: '/productos/servicios',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProveedoresIndexRoute = ErpProveedoresIndexRouteImport.update({
  id: '/proveedores/',
  path: '/proveedores/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpProveedoresIdRoute = ErpProveedoresIdRouteImport.update({
  id: '/proveedores/$id',
  path: '/proveedores/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpReportesIndexRoute = ErpReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpReportesCobranzasRoute = ErpReportesCobranzasRouteImport.update({
  id: '/reportes/cobranzas',
  path: '/reportes/cobranzas',
  getParentRoute: () => ErpRoute,
} as any)
const ErpReportesInventarioRoute = ErpReportesInventarioRouteImport.update({
  id: '/reportes/inventario',
  path: '/reportes/inventario',
  getParentRoute: () => ErpRoute,
} as any)
const ErpReportesTallerRoute = ErpReportesTallerRouteImport.update({
  id: '/reportes/taller',
  path: '/reportes/taller',
  getParentRoute: () => ErpRoute,
} as any)
const ErpReportesVentasRoute = ErpReportesVentasRouteImport.update({
  id: '/reportes/ventas',
  path: '/reportes/ventas',
  getParentRoute: () => ErpRoute,
} as any)
const ErpUsuariosIndexRoute = ErpUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpUsuariosIdRoute = ErpUsuariosIdRouteImport.update({
  id: '/usuarios/$id',
  path: '/usuarios/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpUsuariosPermisosRoute = ErpUsuariosPermisosRouteImport.update({
  id: '/usuarios/permisos',
  path: '/usuarios/permisos',
  getParentRoute: () => ErpRoute,
} as any)
const ErpUsuariosRolesRoute = ErpUsuariosRolesRouteImport.update({
  id: '/usuarios/roles',
  path: '/usuarios/roles',
  getParentRoute: () => ErpRoute,
} as any)
const ErpUsuariosSedesRoute = ErpUsuariosSedesRouteImport.update({
  id: '/usuarios/sedes',
  path: '/usuarios/sedes',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerBahiasIndexRoute = ErpTallerBahiasIndexRouteImport.update({
  id: '/taller/bahias/',
  path: '/taller/bahias/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerCalidadIndexRoute = ErpTallerCalidadIndexRouteImport.update({
  id: '/taller/calidad/',
  path: '/taller/calidad/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerCitasIndexRoute = ErpTallerCitasIndexRouteImport.update({
  id: '/taller/citas/',
  path: '/taller/citas/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerDiagnosticosIndexRoute =
  ErpTallerDiagnosticosIndexRouteImport.update({
    id: '/taller/diagnosticos/',
    path: '/taller/diagnosticos/',
    getParentRoute: () => ErpRoute,
  } as any)
const ErpTallerEntregasIndexRoute = ErpTallerEntregasIndexRouteImport.update({
  id: '/taller/entregas/',
  path: '/taller/entregas/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerHistorialIndexRoute = ErpTallerHistorialIndexRouteImport.update({
  id: '/taller/historial/',
  path: '/taller/historial/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerInspeccionesIndexRoute =
  ErpTallerInspeccionesIndexRouteImport.update({
    id: '/taller/inspecciones/',
    path: '/taller/inspecciones/',
    getParentRoute: () => ErpRoute,
  } as any)
const ErpTallerInspeccionesIdRoute = ErpTallerInspeccionesIdRouteImport.update({
  id: '/taller/inspecciones/$id',
  path: '/taller/inspecciones/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerOrdenesIndexRoute = ErpTallerOrdenesIndexRouteImport.update({
  id: '/taller/ordenes/',
  path: '/taller/ordenes/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerOrdenesIdRoute = ErpTallerOrdenesIdRouteImport.update({
  id: '/taller/ordenes/$id',
  path: '/taller/ordenes/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerPresupuestosIndexRoute =
  ErpTallerPresupuestosIndexRouteImport.update({
    id: '/taller/presupuestos/',
    path: '/taller/presupuestos/',
    getParentRoute: () => ErpRoute,
  } as any)
const ErpTallerRecepcionIndexRoute = ErpTallerRecepcionIndexRouteImport.update({
  id: '/taller/recepcion/',
  path: '/taller/recepcion/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerVehiculosIndexRoute = ErpTallerVehiculosIndexRouteImport.update({
  id: '/taller/vehiculos/',
  path: '/taller/vehiculos/',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerVehiculosIdRoute = ErpTallerVehiculosIdRouteImport.update({
  id: '/taller/vehiculos/$id',
  path: '/taller/vehiculos/$id',
  getParentRoute: () => ErpRoute,
} as any)
const ErpTallerWipIndexRoute = ErpTallerWipIndexRouteImport.update({
  id: '/taller/wip/',
  path: '/taller/wip/',
  getParentRoute: () => ErpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes/$id': typeof ErpClientesIdRoute
  '/compras/cotizaciones': typeof ErpComprasCotizacionesRoute
  '/compras/gastos': typeof ErpComprasGastosRoute
  '/compras/nueva': typeof ErpComprasNuevaRoute
  '/compras/ordenes': typeof ErpComprasOrdenesRoute
  '/inventario/ajustes': typeof ErpInventarioAjustesRoute
  '/inventario/critico': typeof ErpInventarioCriticoRoute
  '/inventario/devoluciones': typeof ErpInventarioDevolucionesRoute
  '/inventario/fisico': typeof ErpInventarioFisicoRoute
  '/inventario/historico': typeof ErpInventarioHistoricoRoute
  '/inventario/kardex': typeof ErpInventarioKardexRoute
  '/inventario/movimientos': typeof ErpInventarioMovimientosRoute
  '/inventario/transferencias': typeof ErpInventarioTransferenciasRoute
  '/pos/anticipos': typeof ErpPosAnticiposRoute
  '/pos/cajas': typeof ErpPosCajasRoute
  '/pos/venta-rapida': typeof ErpPosVentaRapidaRoute
  '/productos/categorias': typeof ErpProductosCategoriasRoute
  '/productos/descuentos': typeof ErpProductosDescuentosRoute
  '/productos/lineas': typeof ErpProductosLineasRoute
  '/productos/marcas': typeof ErpProductosMarcasRoute
  '/productos/promociones': typeof ErpProductosPromocionesRoute
  '/productos/servicios': typeof ErpProductosServiciosRoute
  '/proveedores/$id': typeof ErpProveedoresIdRoute
  '/reportes/cobranzas': typeof ErpReportesCobranzasRoute
  '/reportes/inventario': typeof ErpReportesInventarioRoute
  '/reportes/taller': typeof ErpReportesTallerRoute
  '/reportes/ventas': typeof ErpReportesVentasRoute
  '/usuarios/$id': typeof ErpUsuariosIdRoute
  '/usuarios/permisos': typeof ErpUsuariosPermisosRoute
  '/usuarios/roles': typeof ErpUsuariosRolesRoute
  '/usuarios/sedes': typeof ErpUsuariosSedesRoute
  '/clientes/': typeof ErpClientesIndexRoute
  '/compras/': typeof ErpComprasIndexRoute
  '/configuracion/': typeof ErpConfiguracionIndexRoute
  '/inventario/': typeof ErpInventarioIndexRoute
  '/pos/': typeof ErpPosIndexRoute
  '/productos/': typeof ErpProductosIndexRoute
  '/proveedores/': typeof ErpProveedoresIndexRoute
  '/reportes/': typeof ErpReportesIndexRoute
  '/usuarios/': typeof ErpUsuariosIndexRoute
  '/taller/inspecciones/$id': typeof ErpTallerInspeccionesIdRoute
  '/taller/ordenes/$id': typeof ErpTallerOrdenesIdRoute
  '/taller/vehiculos/$id': typeof ErpTallerVehiculosIdRoute
  '/taller/bahias/': typeof ErpTallerBahiasIndexRoute
  '/taller/calidad/': typeof ErpTallerCalidadIndexRoute
  '/taller/citas/': typeof ErpTallerCitasIndexRoute
  '/taller/diagnosticos/': typeof ErpTallerDiagnosticosIndexRoute
  '/taller/entregas/': typeof ErpTallerEntregasIndexRoute
  '/taller/historial/': typeof ErpTallerHistorialIndexRoute
  '/taller/inspecciones/': typeof ErpTallerInspeccionesIndexRoute
  '/taller/ordenes/': typeof ErpTallerOrdenesIndexRoute
  '/taller/presupuestos/': typeof ErpTallerPresupuestosIndexRoute
  '/taller/recepcion/': typeof ErpTallerRecepcionIndexRoute
  '/taller/vehiculos/': typeof ErpTallerVehiculosIndexRoute
  '/taller/wip/': typeof ErpTallerWipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes/$id': typeof ErpClientesIdRoute
  '/compras/cotizaciones': typeof ErpComprasCotizacionesRoute
  '/compras/gastos': typeof ErpComprasGastosRoute
  '/compras/nueva': typeof ErpComprasNuevaRoute
  '/compras/ordenes': typeof ErpComprasOrdenesRoute
  '/inventario/ajustes': typeof ErpInventarioAjustesRoute
  '/inventario/critico': typeof ErpInventarioCriticoRoute
  '/inventario/devoluciones': typeof ErpInventarioDevolucionesRoute
  '/inventario/fisico': typeof ErpInventarioFisicoRoute
  '/inventario/historico': typeof ErpInventarioHistoricoRoute
  '/inventario/kardex': typeof ErpInventarioKardexRoute
  '/inventario/movimientos': typeof ErpInventarioMovimientosRoute
  '/inventario/transferencias': typeof ErpInventarioTransferenciasRoute
  '/pos/anticipos': typeof ErpPosAnticiposRoute
  '/pos/cajas': typeof ErpPosCajasRoute
  '/pos/venta-rapida': typeof ErpPosVentaRapidaRoute
  '/productos/categorias': typeof ErpProductosCategoriasRoute
  '/productos/descuentos': typeof ErpProductosDescuentosRoute
  '/productos/lineas': typeof ErpProductosLineasRoute
  '/productos/marcas': typeof ErpProductosMarcasRoute
  '/productos/promociones': typeof ErpProductosPromocionesRoute
  '/productos/servicios': typeof ErpProductosServiciosRoute
  '/proveedores/$id': typeof ErpProveedoresIdRoute
  '/reportes/cobranzas': typeof ErpReportesCobranzasRoute
  '/reportes/inventario': typeof ErpReportesInventarioRoute
  '/reportes/taller': typeof ErpReportesTallerRoute
  '/reportes/ventas': typeof ErpReportesVentasRoute
  '/usuarios/$id': typeof ErpUsuariosIdRoute
  '/usuarios/permisos': typeof ErpUsuariosPermisosRoute
  '/usuarios/roles': typeof ErpUsuariosRolesRoute
  '/usuarios/sedes': typeof ErpUsuariosSedesRoute
  '/clientes': typeof ErpClientesIndexRoute
  '/compras': typeof ErpComprasIndexRoute
  '/configuracion': typeof ErpConfiguracionIndexRoute
  '/inventario': typeof ErpInventarioIndexRoute
  '/pos': typeof ErpPosIndexRoute
  '/productos': typeof ErpProductosIndexRoute
  '/proveedores': typeof ErpProveedoresIndexRoute
  '/reportes': typeof ErpReportesIndexRoute
  '/usuarios': typeof ErpUsuariosIndexRoute
  '/taller/inspecciones/$id': typeof ErpTallerInspeccionesIdRoute
  '/taller/ordenes/$id': typeof ErpTallerOrdenesIdRoute
  '/taller/vehiculos/$id': typeof ErpTallerVehiculosIdRoute
  '/taller/bahias': typeof ErpTallerBahiasIndexRoute
  '/taller/calidad': typeof ErpTallerCalidadIndexRoute
  '/taller/citas': typeof ErpTallerCitasIndexRoute
  '/taller/diagnosticos': typeof ErpTallerDiagnosticosIndexRoute
  '/taller/entregas': typeof ErpTallerEntregasIndexRoute
  '/taller/historial': typeof ErpTallerHistorialIndexRoute
  '/taller/inspecciones': typeof ErpTallerInspeccionesIndexRoute
  '/taller/ordenes': typeof ErpTallerOrdenesIndexRoute
  '/taller/presupuestos': typeof ErpTallerPresupuestosIndexRoute
  '/taller/recepcion': typeof ErpTallerRecepcionIndexRoute
  '/taller/vehiculos': typeof ErpTallerVehiculosIndexRoute
  '/taller/wip': typeof ErpTallerWipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_erp': typeof ErpRouteWithChildren
  '/_erp/clientes/$id': typeof ErpClientesIdRoute
  '/_erp/compras/cotizaciones': typeof ErpComprasCotizacionesRoute
  '/_erp/compras/gastos': typeof ErpComprasGastosRoute
  '/_erp/compras/nueva': typeof ErpComprasNuevaRoute
  '/_erp/compras/ordenes': typeof ErpComprasOrdenesRoute
  '/_erp/inventario/ajustes': typeof ErpInventarioAjustesRoute
  '/_erp/inventario/critico': typeof ErpInventarioCriticoRoute
  '/_erp/inventario/devoluciones': typeof ErpInventarioDevolucionesRoute
  '/_erp/inventario/fisico': typeof ErpInventarioFisicoRoute
  '/_erp/inventario/historico': typeof ErpInventarioHistoricoRoute
  '/_erp/inventario/kardex': typeof ErpInventarioKardexRoute
  '/_erp/inventario/movimientos': typeof ErpInventarioMovimientosRoute
  '/_erp/inventario/transferencias': typeof ErpInventarioTransferenciasRoute
  '/_erp/pos/anticipos': typeof ErpPosAnticiposRoute
  '/_erp/pos/cajas': typeof ErpPosCajasRoute
  '/_erp/pos/venta-rapida': typeof ErpPosVentaRapidaRoute
  '/_erp/productos/categorias': typeof ErpProductosCategoriasRoute
  '/_erp/productos/descuentos': typeof ErpProductosDescuentosRoute
  '/_erp/productos/lineas': typeof ErpProductosLineasRoute
  '/_erp/productos/marcas': typeof ErpProductosMarcasRoute
  '/_erp/productos/promociones': typeof ErpProductosPromocionesRoute
  '/_erp/productos/servicios': typeof ErpProductosServiciosRoute
  '/_erp/proveedores/$id': typeof ErpProveedoresIdRoute
  '/_erp/reportes/cobranzas': typeof ErpReportesCobranzasRoute
  '/_erp/reportes/inventario': typeof ErpReportesInventarioRoute
  '/_erp/reportes/taller': typeof ErpReportesTallerRoute
  '/_erp/reportes/ventas': typeof ErpReportesVentasRoute
  '/_erp/usuarios/$id': typeof ErpUsuariosIdRoute
  '/_erp/usuarios/permisos': typeof ErpUsuariosPermisosRoute
  '/_erp/usuarios/roles': typeof ErpUsuariosRolesRoute
  '/_erp/usuarios/sedes': typeof ErpUsuariosSedesRoute
  '/_erp/clientes/': typeof ErpClientesIndexRoute
  '/_erp/compras/': typeof ErpComprasIndexRoute
  '/_erp/configuracion/': typeof ErpConfiguracionIndexRoute
  '/_erp/inventario/': typeof ErpInventarioIndexRoute
  '/_erp/pos/': typeof ErpPosIndexRoute
  '/_erp/productos/': typeof ErpProductosIndexRoute
  '/_erp/proveedores/': typeof ErpProveedoresIndexRoute
  '/_erp/reportes/': typeof ErpReportesIndexRoute
  '/_erp/usuarios/': typeof ErpUsuariosIndexRoute
  '/_erp/taller/inspecciones/$id': typeof ErpTallerInspeccionesIdRoute
  '/_erp/taller/ordenes/$id': typeof ErpTallerOrdenesIdRoute
  '/_erp/taller/vehiculos/$id': typeof ErpTallerVehiculosIdRoute
  '/_erp/taller/bahias/': typeof ErpTallerBahiasIndexRoute
  '/_erp/taller/calidad/': typeof ErpTallerCalidadIndexRoute
  '/_erp/taller/citas/': typeof ErpTallerCitasIndexRoute
  '/_erp/taller/diagnosticos/': typeof ErpTallerDiagnosticosIndexRoute
  '/_erp/taller/entregas/': typeof ErpTallerEntregasIndexRoute
  '/_erp/taller/historial/': typeof ErpTallerHistorialIndexRoute
  '/_erp/taller/inspecciones/': typeof ErpTallerInspeccionesIndexRoute
  '/_erp/taller/ordenes/': typeof ErpTallerOrdenesIndexRoute
  '/_erp/taller/presupuestos/': typeof ErpTallerPresupuestosIndexRoute
  '/_erp/taller/recepcion/': typeof ErpTallerRecepcionIndexRoute
  '/_erp/taller/vehiculos/': typeof ErpTallerVehiculosIndexRoute
  '/_erp/taller/wip/': typeof ErpTallerWipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes/$id'
    | '/compras/cotizaciones'
    | '/compras/gastos'
    | '/compras/nueva'
    | '/compras/ordenes'
    | '/inventario/ajustes'
    | '/inventario/critico'
    | '/inventario/devoluciones'
    | '/inventario/fisico'
    | '/inventario/historico'
    | '/inventario/kardex'
    | '/inventario/movimientos'
    | '/inventario/transferencias'
    | '/pos/anticipos'
    | '/pos/cajas'
    | '/pos/venta-rapida'
    | '/productos/categorias'
    | '/productos/descuentos'
    | '/productos/lineas'
    | '/productos/marcas'
    | '/productos/promociones'
    | '/productos/servicios'
    | '/proveedores/$id'
    | '/reportes/cobranzas'
    | '/reportes/inventario'
    | '/reportes/taller'
    | '/reportes/ventas'
    | '/usuarios/$id'
    | '/usuarios/permisos'
    | '/usuarios/roles'
    | '/usuarios/sedes'
    | '/clientes/'
    | '/compras/'
    | '/configuracion/'
    | '/inventario/'
    | '/pos/'
    | '/productos/'
    | '/proveedores/'
    | '/reportes/'
    | '/usuarios/'
    | '/taller/inspecciones/$id'
    | '/taller/ordenes/$id'
    | '/taller/vehiculos/$id'
    | '/taller/bahias/'
    | '/taller/calidad/'
    | '/taller/citas/'
    | '/taller/diagnosticos/'
    | '/taller/entregas/'
    | '/taller/historial/'
    | '/taller/inspecciones/'
    | '/taller/ordenes/'
    | '/taller/presupuestos/'
    | '/taller/recepcion/'
    | '/taller/vehiculos/'
    | '/taller/wip/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes/$id'
    | '/compras/cotizaciones'
    | '/compras/gastos'
    | '/compras/nueva'
    | '/compras/ordenes'
    | '/inventario/ajustes'
    | '/inventario/critico'
    | '/inventario/devoluciones'
    | '/inventario/fisico'
    | '/inventario/historico'
    | '/inventario/kardex'
    | '/inventario/movimientos'
    | '/inventario/transferencias'
    | '/pos/anticipos'
    | '/pos/cajas'
    | '/pos/venta-rapida'
    | '/productos/categorias'
    | '/productos/descuentos'
    | '/productos/lineas'
    | '/productos/marcas'
    | '/productos/promociones'
    | '/productos/servicios'
    | '/proveedores/$id'
    | '/reportes/cobranzas'
    | '/reportes/inventario'
    | '/reportes/taller'
    | '/reportes/ventas'
    | '/usuarios/$id'
    | '/usuarios/permisos'
    | '/usuarios/roles'
    | '/usuarios/sedes'
    | '/clientes'
    | '/compras'
    | '/configuracion'
    | '/inventario'
    | '/pos'
    | '/productos'
    | '/proveedores'
    | '/reportes'
    | '/usuarios'
    | '/taller/inspecciones/$id'
    | '/taller/ordenes/$id'
    | '/taller/vehiculos/$id'
    | '/taller/bahias'
    | '/taller/calidad'
    | '/taller/citas'
    | '/taller/diagnosticos'
    | '/taller/entregas'
    | '/taller/historial'
    | '/taller/inspecciones'
    | '/taller/ordenes'
    | '/taller/presupuestos'
    | '/taller/recepcion'
    | '/taller/vehiculos'
    | '/taller/wip'
  id:
    | '__root__'
    | '/'
    | '/_erp'
    | '/_erp/clientes/$id'
    | '/_erp/compras/cotizaciones'
    | '/_erp/compras/gastos'
    | '/_erp/compras/nueva'
    | '/_erp/compras/ordenes'
    | '/_erp/inventario/ajustes'
    | '/_erp/inventario/critico'
    | '/_erp/inventario/devoluciones'
    | '/_erp/inventario/fisico'
    | '/_erp/inventario/historico'
    | '/_erp/inventario/kardex'
    | '/_erp/inventario/movimientos'
    | '/_erp/inventario/transferencias'
    | '/_erp/pos/anticipos'
    | '/_erp/pos/cajas'
    | '/_erp/pos/venta-rapida'
    | '/_erp/productos/categorias'
    | '/_erp/productos/descuentos'
    | '/_erp/productos/lineas'
    | '/_erp/productos/marcas'
    | '/_erp/productos/promociones'
    | '/_erp/productos/servicios'
    | '/_erp/proveedores/$id'
    | '/_erp/reportes/cobranzas'
    | '/_erp/reportes/inventario'
    | '/_erp/reportes/taller'
    | '/_erp/reportes/ventas'
    | '/_erp/usuarios/$id'
    | '/_erp/usuarios/permisos'
    | '/_erp/usuarios/roles'
    | '/_erp/usuarios/sedes'
    | '/_erp/clientes/'
    | '/_erp/compras/'
    | '/_erp/configuracion/'
    | '/_erp/inventario/'
    | '/_erp/pos/'
    | '/_erp/productos/'
    | '/_erp/proveedores/'
    | '/_erp/reportes/'
    | '/_erp/usuarios/'
    | '/_erp/taller/inspecciones/$id'
    | '/_erp/taller/ordenes/$id'
    | '/_erp/taller/vehiculos/$id'
    | '/_erp/taller/bahias/'
    | '/_erp/taller/calidad/'
    | '/_erp/taller/citas/'
    | '/_erp/taller/diagnosticos/'
    | '/_erp/taller/entregas/'
    | '/_erp/taller/historial/'
    | '/_erp/taller/inspecciones/'
    | '/_erp/taller/ordenes/'
    | '/_erp/taller/presupuestos/'
    | '/_erp/taller/recepcion/'
    | '/_erp/taller/vehiculos/'
    | '/_erp/taller/wip/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErpRoute: typeof ErpRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_erp': {
      id: '/_erp'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_erp/clientes/': {
      id: '/_erp/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ErpClientesIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/clientes/$id': {
      id: '/_erp/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ErpClientesIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/compras/': {
      id: '/_erp/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof ErpComprasIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/compras/cotizaciones': {
      id: '/_erp/compras/cotizaciones'
      path: '/compras/cotizaciones'
      fullPath: '/compras/cotizaciones'
      preLoaderRoute: typeof ErpComprasCotizacionesRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/compras/gastos': {
      id: '/_erp/compras/gastos'
      path: '/compras/gastos'
      fullPath: '/compras/gastos'
      preLoaderRoute: typeof ErpComprasGastosRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/compras/nueva': {
      id: '/_erp/compras/nueva'
      path: '/compras/nueva'
      fullPath: '/compras/nueva'
      preLoaderRoute: typeof ErpComprasNuevaRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/compras/ordenes': {
      id: '/_erp/compras/ordenes'
      path: '/compras/ordenes'
      fullPath: '/compras/ordenes'
      preLoaderRoute: typeof ErpComprasOrdenesRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/configuracion/': {
      id: '/_erp/configuracion/'
      path: '/configuracion'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof ErpConfiguracionIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/inventario/': {
      id: '/_erp/inventario/'
      path: '/inventario'
      fullPath: '/inventario/'
      preLoaderRoute: typeof ErpInventarioIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/inventario/ajustes': {
      id: '/_erp/inventario/ajustes'
      path: '/inventario/ajustes'
      fullPath: '/inventario/ajustes'
      preLoaderRoute: typeof ErpInventarioAjustesRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/inventario/critico': {
      id: '/_erp/inventario/critico'
      path: '/inventario/critico'
      fullPath: '/inventario/critico'
      preLoaderRoute: typeof ErpInventarioCriticoRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/inventario/devoluciones': {
      id: '/_erp/inventario/devoluciones'
      path: '/inventario/devoluciones'
      fullPath: '/inventario/devoluciones'
      preLoaderRoute: typeof ErpInventarioDevolucionesRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/inventario/fisico': {
      id: '/_erp/inventario/fisico'
      path: '/inventario/fisico'
      fullPath: '/inventario/fisico'
      preLoaderRoute: typeof ErpInventarioFisicoRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/inventario/historico': {
      id: '/_erp/inventario/historico'
      path: '/inventario/historico'
      fullPath: '/inventario/historico'
      preLoaderRoute: typeof ErpInventarioHistoricoRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/inventario/kardex': {
      id: '/_erp/inventario/kardex'
      path: '/inventario/kardex'
      fullPath: '/inventario/kardex'
      preLoaderRoute: typeof ErpInventarioKardexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/inventario/movimientos': {
      id: '/_erp/inventario/movimientos'
      path: '/inventario/movimientos'
      fullPath: '/inventario/movimientos'
      preLoaderRoute: typeof ErpInventarioMovimientosRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/inventario/transferencias': {
      id: '/_erp/inventario/transferencias'
      path: '/inventario/transferencias'
      fullPath: '/inventario/transferencias'
      preLoaderRoute: typeof ErpInventarioTransferenciasRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/pos/': {
      id: '/_erp/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof ErpPosIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/pos/anticipos': {
      id: '/_erp/pos/anticipos'
      path: '/pos/anticipos'
      fullPath: '/pos/anticipos'
      preLoaderRoute: typeof ErpPosAnticiposRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/pos/cajas': {
      id: '/_erp/pos/cajas'
      path: '/pos/cajas'
      fullPath: '/pos/cajas'
      preLoaderRoute: typeof ErpPosCajasRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/pos/venta-rapida': {
      id: '/_erp/pos/venta-rapida'
      path: '/pos/venta-rapida'
      fullPath: '/pos/venta-rapida'
      preLoaderRoute: typeof ErpPosVentaRapidaRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/productos/': {
      id: '/_erp/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ErpProductosIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/productos/categorias': {
      id: '/_erp/productos/categorias'
      path: '/productos/categorias'
      fullPath: '/productos/categorias'
      preLoaderRoute: typeof ErpProductosCategoriasRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/productos/descuentos': {
      id: '/_erp/productos/descuentos'
      path: '/productos/descuentos'
      fullPath: '/productos/descuentos'
      preLoaderRoute: typeof ErpProductosDescuentosRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/productos/lineas': {
      id: '/_erp/productos/lineas'
      path: '/productos/lineas'
      fullPath: '/productos/lineas'
      preLoaderRoute: typeof ErpProductosLineasRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/productos/marcas': {
      id: '/_erp/productos/marcas'
      path: '/productos/marcas'
      fullPath: '/productos/marcas'
      preLoaderRoute: typeof ErpProductosMarcasRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/productos/promociones': {
      id: '/_erp/productos/promociones'
      path: '/productos/promociones'
      fullPath: '/productos/promociones'
      preLoaderRoute: typeof ErpProductosPromocionesRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/productos/servicios': {
      id: '/_erp/productos/servicios'
      path: '/productos/servicios'
      fullPath: '/productos/servicios'
      preLoaderRoute: typeof ErpProductosServiciosRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/proveedores/': {
      id: '/_erp/proveedores/'
      path: '/proveedores'
      fullPath: '/proveedores/'
      preLoaderRoute: typeof ErpProveedoresIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/proveedores/$id': {
      id: '/_erp/proveedores/$id'
      path: '/proveedores/$id'
      fullPath: '/proveedores/$id'
      preLoaderRoute: typeof ErpProveedoresIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/reportes/': {
      id: '/_erp/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof ErpReportesIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/reportes/cobranzas': {
      id: '/_erp/reportes/cobranzas'
      path: '/reportes/cobranzas'
      fullPath: '/reportes/cobranzas'
      preLoaderRoute: typeof ErpReportesCobranzasRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/reportes/inventario': {
      id: '/_erp/reportes/inventario'
      path: '/reportes/inventario'
      fullPath: '/reportes/inventario'
      preLoaderRoute: typeof ErpReportesInventarioRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/reportes/taller': {
      id: '/_erp/reportes/taller'
      path: '/reportes/taller'
      fullPath: '/reportes/taller'
      preLoaderRoute: typeof ErpReportesTallerRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/reportes/ventas': {
      id: '/_erp/reportes/ventas'
      path: '/reportes/ventas'
      fullPath: '/reportes/ventas'
      preLoaderRoute: typeof ErpReportesVentasRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/usuarios/': {
      id: '/_erp/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof ErpUsuariosIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/usuarios/$id': {
      id: '/_erp/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/usuarios/$id'
      preLoaderRoute: typeof ErpUsuariosIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/usuarios/permisos': {
      id: '/_erp/usuarios/permisos'
      path: '/usuarios/permisos'
      fullPath: '/usuarios/permisos'
      preLoaderRoute: typeof ErpUsuariosPermisosRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/usuarios/roles': {
      id: '/_erp/usuarios/roles'
      path: '/usuarios/roles'
      fullPath: '/usuarios/roles'
      preLoaderRoute: typeof ErpUsuariosRolesRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/usuarios/sedes': {
      id: '/_erp/usuarios/sedes'
      path: '/usuarios/sedes'
      fullPath: '/usuarios/sedes'
      preLoaderRoute: typeof ErpUsuariosSedesRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/bahias/': {
      id: '/_erp/taller/bahias/'
      path: '/taller/bahias'
      fullPath: '/taller/bahias/'
      preLoaderRoute: typeof ErpTallerBahiasIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/calidad/': {
      id: '/_erp/taller/calidad/'
      path: '/taller/calidad'
      fullPath: '/taller/calidad/'
      preLoaderRoute: typeof ErpTallerCalidadIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/citas/': {
      id: '/_erp/taller/citas/'
      path: '/taller/citas'
      fullPath: '/taller/citas/'
      preLoaderRoute: typeof ErpTallerCitasIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/diagnosticos/': {
      id: '/_erp/taller/diagnosticos/'
      path: '/taller/diagnosticos'
      fullPath: '/taller/diagnosticos/'
      preLoaderRoute: typeof ErpTallerDiagnosticosIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/entregas/': {
      id: '/_erp/taller/entregas/'
      path: '/taller/entregas'
      fullPath: '/taller/entregas/'
      preLoaderRoute: typeof ErpTallerEntregasIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/historial/': {
      id: '/_erp/taller/historial/'
      path: '/taller/historial'
      fullPath: '/taller/historial/'
      preLoaderRoute: typeof ErpTallerHistorialIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/inspecciones/': {
      id: '/_erp/taller/inspecciones/'
      path: '/taller/inspecciones'
      fullPath: '/taller/inspecciones/'
      preLoaderRoute: typeof ErpTallerInspeccionesIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/inspecciones/$id': {
      id: '/_erp/taller/inspecciones/$id'
      path: '/taller/inspecciones/$id'
      fullPath: '/taller/inspecciones/$id'
      preLoaderRoute: typeof ErpTallerInspeccionesIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/ordenes/': {
      id: '/_erp/taller/ordenes/'
      path: '/taller/ordenes'
      fullPath: '/taller/ordenes/'
      preLoaderRoute: typeof ErpTallerOrdenesIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/ordenes/$id': {
      id: '/_erp/taller/ordenes/$id'
      path: '/taller/ordenes/$id'
      fullPath: '/taller/ordenes/$id'
      preLoaderRoute: typeof ErpTallerOrdenesIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/presupuestos/': {
      id: '/_erp/taller/presupuestos/'
      path: '/taller/presupuestos'
      fullPath: '/taller/presupuestos/'
      preLoaderRoute: typeof ErpTallerPresupuestosIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/recepcion/': {
      id: '/_erp/taller/recepcion/'
      path: '/taller/recepcion'
      fullPath: '/taller/recepcion/'
      preLoaderRoute: typeof ErpTallerRecepcionIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/vehiculos/': {
      id: '/_erp/taller/vehiculos/'
      path: '/taller/vehiculos'
      fullPath: '/taller/vehiculos/'
      preLoaderRoute: typeof ErpTallerVehiculosIndexRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/vehiculos/$id': {
      id: '/_erp/taller/vehiculos/$id'
      path: '/taller/vehiculos/$id'
      fullPath: '/taller/vehiculos/$id'
      preLoaderRoute: typeof ErpTallerVehiculosIdRouteImport
      parentRoute: typeof ErpRoute
    }
    '/_erp/taller/wip/': {
      id: '/_erp/taller/wip/'
      path: '/taller/wip'
      fullPath: '/taller/wip/'
      preLoaderRoute: typeof ErpTallerWipIndexRouteImport
      parentRoute: typeof ErpRoute
    }
  }
}

interface ErpRouteChildren {
  ErpClientesIdRoute: typeof ErpClientesIdRoute
  ErpComprasCotizacionesRoute: typeof ErpComprasCotizacionesRoute
  ErpComprasGastosRoute: typeof ErpComprasGastosRoute
  ErpComprasNuevaRoute: typeof ErpComprasNuevaRoute
  ErpComprasOrdenesRoute: typeof ErpComprasOrdenesRoute
  ErpInventarioAjustesRoute: typeof ErpInventarioAjustesRoute
  ErpInventarioCriticoRoute: typeof ErpInventarioCriticoRoute
  ErpInventarioDevolucionesRoute: typeof ErpInventarioDevolucionesRoute
  ErpInventarioFisicoRoute: typeof ErpInventarioFisicoRoute
  ErpInventarioHistoricoRoute: typeof ErpInventarioHistoricoRoute
  ErpInventarioKardexRoute: typeof ErpInventarioKardexRoute
  ErpInventarioMovimientosRoute: typeof ErpInventarioMovimientosRoute
  ErpInventarioTransferenciasRoute: typeof ErpInventarioTransferenciasRoute
  ErpPosAnticiposRoute: typeof ErpPosAnticiposRoute
  ErpPosCajasRoute: typeof ErpPosCajasRoute
  ErpPosVentaRapidaRoute: typeof ErpPosVentaRapidaRoute
  ErpProductosCategoriasRoute: typeof ErpProductosCategoriasRoute
  ErpProductosDescuentosRoute: typeof ErpProductosDescuentosRoute
  ErpProductosLineasRoute: typeof ErpProductosLineasRoute
  ErpProductosMarcasRoute: typeof ErpProductosMarcasRoute
  ErpProductosPromocionesRoute: typeof ErpProductosPromocionesRoute
  ErpProductosServiciosRoute: typeof ErpProductosServiciosRoute
  ErpProveedoresIdRoute: typeof ErpProveedoresIdRoute
  ErpReportesCobranzasRoute: typeof ErpReportesCobranzasRoute
  ErpReportesInventarioRoute: typeof ErpReportesInventarioRoute
  ErpReportesTallerRoute: typeof ErpReportesTallerRoute
  ErpReportesVentasRoute: typeof ErpReportesVentasRoute
  ErpUsuariosIdRoute: typeof ErpUsuariosIdRoute
  ErpUsuariosPermisosRoute: typeof ErpUsuariosPermisosRoute
  ErpUsuariosRolesRoute: typeof ErpUsuariosRolesRoute
  ErpUsuariosSedesRoute: typeof ErpUsuariosSedesRoute
  ErpClientesIndexRoute: typeof ErpClientesIndexRoute
  ErpComprasIndexRoute: typeof ErpComprasIndexRoute
  ErpConfiguracionIndexRoute: typeof ErpConfiguracionIndexRoute
  ErpInventarioIndexRoute: typeof ErpInventarioIndexRoute
  ErpPosIndexRoute: typeof ErpPosIndexRoute
  ErpProductosIndexRoute: typeof ErpProductosIndexRoute
  ErpProveedoresIndexRoute: typeof ErpProveedoresIndexRoute
  ErpReportesIndexRoute: typeof ErpReportesIndexRoute
  ErpUsuariosIndexRoute: typeof ErpUsuariosIndexRoute
  ErpTallerInspeccionesIdRoute: typeof ErpTallerInspeccionesIdRoute
  ErpTallerOrdenesIdRoute: typeof ErpTallerOrdenesIdRoute
  ErpTallerVehiculosIdRoute: typeof ErpTallerVehiculosIdRoute
  ErpTallerBahiasIndexRoute: typeof ErpTallerBahiasIndexRoute
  ErpTallerCalidadIndexRoute: typeof ErpTallerCalidadIndexRoute
  ErpTallerCitasIndexRoute: typeof ErpTallerCitasIndexRoute
  ErpTallerDiagnosticosIndexRoute: typeof ErpTallerDiagnosticosIndexRoute
  ErpTallerEntregasIndexRoute: typeof ErpTallerEntregasIndexRoute
  ErpTallerHistorialIndexRoute: typeof ErpTallerHistorialIndexRoute
  ErpTallerInspeccionesIndexRoute: typeof ErpTallerInspeccionesIndexRoute
  ErpTallerOrdenesIndexRoute: typeof ErpTallerOrdenesIndexRoute
  ErpTallerPresupuestosIndexRoute: typeof ErpTallerPresupuestosIndexRoute
  ErpTallerRecepcionIndexRoute: typeof ErpTallerRecepcionIndexRoute
  ErpTallerVehiculosIndexRoute: typeof ErpTallerVehiculosIndexRoute
  ErpTallerWipIndexRoute: typeof ErpTallerWipIndexRoute
}

const ErpRouteChildren: ErpRouteChildren = {
  ErpClientesIdRoute: ErpClientesIdRoute,
  ErpComprasCotizacionesRoute: ErpComprasCotizacionesRoute,
  ErpComprasGastosRoute: ErpComprasGastosRoute,
  ErpComprasNuevaRoute: ErpComprasNuevaRoute,
  ErpComprasOrdenesRoute: ErpComprasOrdenesRoute,
  ErpInventarioAjustesRoute: ErpInventarioAjustesRoute,
  ErpInventarioCriticoRoute: ErpInventarioCriticoRoute,
  ErpInventarioDevolucionesRoute: ErpInventarioDevolucionesRoute,
  ErpInventarioFisicoRoute: ErpInventarioFisicoRoute,
  ErpInventarioHistoricoRoute: ErpInventarioHistoricoRoute,
  ErpInventarioKardexRoute: ErpInventarioKardexRoute,
  ErpInventarioMovimientosRoute: ErpInventarioMovimientosRoute,
  ErpInventarioTransferenciasRoute: ErpInventarioTransferenciasRoute,
  ErpPosAnticiposRoute: ErpPosAnticiposRoute,
  ErpPosCajasRoute: ErpPosCajasRoute,
  ErpPosVentaRapidaRoute: ErpPosVentaRapidaRoute,
  ErpProductosCategoriasRoute: ErpProductosCategoriasRoute,
  ErpProductosDescuentosRoute: ErpProductosDescuentosRoute,
  ErpProductosLineasRoute: ErpProductosLineasRoute,
  ErpProductosMarcasRoute: ErpProductosMarcasRoute,
  ErpProductosPromocionesRoute: ErpProductosPromocionesRoute,
  ErpProductosServiciosRoute: ErpProductosServiciosRoute,
  ErpProveedoresIdRoute: ErpProveedoresIdRoute,
  ErpReportesCobranzasRoute: ErpReportesCobranzasRoute,
  ErpReportesInventarioRoute: ErpReportesInventarioRoute,
  ErpReportesTallerRoute: ErpReportesTallerRoute,
  ErpReportesVentasRoute: ErpReportesVentasRoute,
  ErpUsuariosIdRoute: ErpUsuariosIdRoute,
  ErpUsuariosPermisosRoute: ErpUsuariosPermisosRoute,
  ErpUsuariosRolesRoute: ErpUsuariosRolesRoute,
  ErpUsuariosSedesRoute: ErpUsuariosSedesRoute,
  ErpClientesIndexRoute: ErpClientesIndexRoute,
  ErpComprasIndexRoute: ErpComprasIndexRoute,
  ErpConfiguracionIndexRoute: ErpConfiguracionIndexRoute,
  ErpInventarioIndexRoute: ErpInventarioIndexRoute,
  ErpPosIndexRoute: ErpPosIndexRoute,
  ErpProductosIndexRoute: ErpProductosIndexRoute,
  ErpProveedoresIndexRoute: ErpProveedoresIndexRoute,
  ErpReportesIndexRoute: ErpReportesIndexRoute,
  ErpUsuariosIndexRoute: ErpUsuariosIndexRoute,
  ErpTallerInspeccionesIdRoute: ErpTallerInspeccionesIdRoute,
  ErpTallerOrdenesIdRoute: ErpTallerOrdenesIdRoute,
  ErpTallerVehiculosIdRoute: ErpTallerVehiculosIdRoute,
  ErpTallerBahiasIndexRoute: ErpTallerBahiasIndexRoute,
  ErpTallerCalidadIndexRoute: ErpTallerCalidadIndexRoute,
  ErpTallerCitasIndexRoute: ErpTallerCitasIndexRoute,
  ErpTallerDiagnosticosIndexRoute: ErpTallerDiagnosticosIndexRoute,
  ErpTallerEntregasIndexRoute: ErpTallerEntregasIndexRoute,
  ErpTallerHistorialIndexRoute: ErpTallerHistorialIndexRoute,
  ErpTallerInspeccionesIndexRoute: ErpTallerInspeccionesIndexRoute,
  ErpTallerOrdenesIndexRoute: ErpTallerOrdenesIndexRoute,
  ErpTallerPresupuestosIndexRoute: ErpTallerPresupuestosIndexRoute,
  ErpTallerRecepcionIndexRoute: ErpTallerRecepcionIndexRoute,
  ErpTallerVehiculosIndexRoute: ErpTallerVehiculosIndexRoute,
  ErpTallerWipIndexRoute: ErpTallerWipIndexRoute,
}

const ErpRouteWithChildren = ErpRoute._addFileChildren(ErpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErpRoute: ErpRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
